<?php require_once '../../vendor/autoload.php' ?>
<?php include_once "../../init.php"; ?>
<?php 
$connection = new PDO($dsn, $dbUsername, $dbPassword, $options);
$paramID = $_POST['id'];
$sql = '
select appointment.AppointmentID, appointment.Price,
profile_d.Name as DName, 
profile_p.Name as PName, doctor.Professional,
schedule.Date, appointment.Time,
appointment.EndTime, appointment.Remark, appointment.TreatmentDesc as Description, appointment.UpdatedBy, profile_u.Name as UName,
    (select profile.name
        from users
        left join profile on profile.ProfileID = users.ProfileID
        where users.UserID = '.$_SESSION['UserID'].'
    )as CName
from appointment appointment
left join schedule on schedule.ScheduleID = appointment.ScheduleID
left join doctor on doctor.DoctorID = schedule.DoctorID
left join patient on patient.PatientID = appointment.PatientID
left join profile as profile_d on profile_d.ProfileID = doctor.ProfileID
left join profile as profile_p on profile_p.ProfileID = patient.ProfileID
left join profile as profile_u on profile_u.ProfileID = appointment.UpdatedBy
where Appointment.AppointmentID = '.$paramID.'
';
?>
<?php
print_r($sql);
$statement = $connection->prepare($sql);
$statement->execute();
$result = $statement->fetch(PDO::FETCH_ASSOC);

$htmlTable = "
<h1 style='text-align:center; text-decoration:italic; text-weight:1000;'>Receipt #".$result['AppointmentID']."</h1>
<div class='div-form'>
    <table class='grid-view'>
        <tbody>
        <tr>
            <td colspan=1>Date</td>
            <td colspan=4>".$result['Date']. ' _ ' . $result['Time'] . ' - ' . $result['EndTime']."</td>
        </tr>
        <tr>
            <td colspan=1>Paid Money</td>
            <td colspan=4>".$result['Price']."</td>
        </tr>
        <tr>
            <td colspan=1>Patient Name</td>
            <td colspan=4>".$result['PName']."</td>
        </tr>
        <tr>
            <td colspan=1>Doctor Name</td>
            <td colspan=4>".$result['DName']."</td>
        </tr>
        <tr>
            <td colspan=1>Doctor Professional</td>
            <td colspan=4>".$result['Professional']."</td>
        </tr>
        <tr>
            <td colspan=1>Description</td>
            <td colspan=4>".$result['Description']."</td>
        </tr>
        <tr>
            <td colspan=1>Treatment Remark</td>
            <td colspan=4>".$result['Remark']."</td>
        </tr>
        <tr>
            <td colspan=1>Generated By</td>
            <td>".$result['CName']."</td>
        </tr>
        <tr>
            <td colspan=1>Approved By</td>
            <td colspan=4>#".$result['UName']."</td>
        </tr>
        <tr>
            <td colspan=1>Generated At</td>
            <td colspan=4>#".date('Y-m-d H:i:s')."</td>
        </tr>
        </tbody>
    </table>
</div>";

$content = $htmlTable;

$stylesheet = file_get_contents('../assets/css/style.css');
$html = '
<html>
<head>
<style>
'.$stylesheet.'
</style>
</head>
<body>

'. $content.'
</body>
</html>
';
$mpdf = new \Mpdf\Mpdf([
	'margin_left' => 20,
	'margin_right' => 15,
	'margin_top' => 48,
	'margin_bottom' => 25,
	'margin_header' => 10,
	'margin_footer' => 10
]);
$mpdf->SetProtection(array('print'));
$mpdf->SetWatermarkText('Receipt of Appointment #' . $result['AppointmentID']);
$mpdf->showWatermarkText = true;
$mpdf->watermark_font = 'DejaVuSansCondensed';
$mpdf->watermarkTextAlpha = 0.1;
$mpdf->SetDisplayMode('fullpage');
$mpdf->WriteHTML($html);

ob_end_clean();

// $mpdf->Output('MyPDF.pdf', 'D');
$mpdf->Output('receipt.pdf','F');
header('Content-type: application/json');
echo json_encode('tdsadsaest');
